### ISSUE TITLE
2023/05/20 19:31:52.412018 server.go:1928: [Error] HERTZ: HTTP2: write response body error when serving 123.123.123.123:20528: http: request method or response status code does not allow body

### ISSUE THREAD

**Issue by kolinfluence** [hertz-contrib/http2#21]
status 304 will return body error here. details here
https://github.com/cloudwego/hertz/issues/786

server.go file.

@welkeyever pls fix this. thx

**Comment by li-jin-gou** [comment]
There was already an issue, so much so that I closed it.
